# Generated by Django 2.2 on 2019-09-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=1000, verbose_name='Pergunta')),
                ('resposta', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Resposta')),
            ],
        ),
    ]
