# Generated by Django 2.2.2 on 2019-09-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='pergunta',
            field=models.CharField(max_length=5000, verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='resposta',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Resposta'),
        ),
    ]
